# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a9b96dfe4295090396f12ebae9d0555b667ba205e44f5550ba1d69cc294fd50f51fd5b24bb97fe56cf0c82d0ae9e7022818c4f6b1be3daf2d03b52654ac3c5ac

test:
  secret_key_base: 463e459c277f36a2a3e4b311fa12661d10d52ee256223c3264e69bc6489345f95cf50f65ed708a2834cbe91d6ada93d130087f9c38f13b3115b19682726312c9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
